# Generated by Django 6.0.1 on 2026-02-15 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('classroom_core', '0003_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
               ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               ('name', models.CharField(max_length=100, unique=True)),
               ('description', models.TextField(blank=True)),
               ('created_at', models.DateTimeField(auto_now_add=True)),
               ('updated_at', models.DateTimeField(auto_now=True)),
               ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='student_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы студентов, зачисленные на курс', related_name='courses_enrolled', to='classroom_core.studentgroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classroom_core.studentgroup'),
        ),
    ]
