# Generated by Django 6.0.1 on 2026-02-18 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('classroom_core', '0004_studentgroup_course_student_groups_and_more'),
       ('file_manager', '0003_alter_fileactivity_file_alter_fileversion_changed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
               ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               ('description', models.TextField(blank=True, help_text='Описание файла(опционально)')),
               ('uploaded_at', models.DateTimeField(auto_now_add=True)),
               ('updated_at', models.DateTimeField(auto_now=True)),
               ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='classroom_core.assignment')),
               ('file', models.ForeignKey(help_text='Файл из файлового хранилища', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='file_manager.file')),
               ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл задания',
                'verbose_name_plural': 'Файлы заданий',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentFileReview',
            fields=[
               ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               ('status', models.CharField(choices=[('pending', 'На проверке'),('approved', 'Принят'),('rejected', 'Отклонен'),('needs_revision', 'Требует доработки')], default='pending', max_length=20)),
               ('feedback', models.TextField(blank=True, help_text='Комментарий преподавателя к файлу')),
               ('points', models.IntegerField(blank=True, help_text='Баллы за файл(опционально)', null=True)),
               ('reviewed_at', models.DateTimeField(auto_now_add=True)),
               ('updated_at', models.DateTimeField(auto_now=True)),
               ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='classroom_core.assignmentfile')),
               ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проверка файла',
                'verbose_name_plural': 'Проверки файлов',
                'ordering': ['-reviewed_at'],
                'unique_together': {('file', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollmentRequest',
            fields=[
               ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               ('status', models.CharField(choices=[('pending', 'На рассмотрении'),('approved', 'Одобрена'),('rejected', 'Отклонена')], default='pending', max_length=20)),
               ('motivation', models.TextField(blank=True, help_text='Расскажите, почему вы хотите записаться на этот курс')),
               ('review_comment', models.TextField(blank=True, help_text='Комментарий преподавателя к решению')),
               ('created_at', models.DateTimeField(auto_now_add=True)),
               ('updated_at', models.DateTimeField(auto_now=True)),
               ('reviewed_at', models.DateTimeField(blank=True, null=True)),
               ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='classroom_core.course')),
               ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollment_requests', to=settings.AUTH_USER_MODEL)),
               ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на запись на курс',
                'verbose_name_plural': 'Заявки на запись на курсы',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
