"""
Django settings for classroom project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default=0):
    value = os.getenv(name)
    if value is None or value == "":
        return default
    try:
        return int(value)
    except ValueError:
        return default


SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-key-change-me")
DEBUG = env_bool("DJANGO_DEBUG", True)
ALLOWED_HOSTS = [host.strip() for host in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",") if host.strip()]
DEFAULT_STORAGE_QUOTA_BYTES = env_int("DEFAULT_STORAGE_QUOTA_BYTES", 5368709120)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'channels',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'file_manager',
    'classroom_core',
    'chat_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'classroom.urls'

TEMPLATES =[
    {
        'BACKEND':'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'classroom.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}
DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS =[
    {
    'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
    'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
    'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
    'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_LOGIN_ON_GET = True

YANDEX_AUTH_CLIENT_ID = os.getenv("YANDEX_AUTH_CLIENT_ID", "")
YANDEX_AUTH_CLIENT_SECRET = os.getenv("YANDEX_AUTH_CLIENT_SECRET", "")
YANDEX_DISK_CLIENT_ID = os.getenv("YANDEX_DISK_CLIENT_ID", YANDEX_AUTH_CLIENT_ID)
YANDEX_DISK_CLIENT_SECRET = os.getenv("YANDEX_DISK_CLIENT_SECRET", YANDEX_AUTH_CLIENT_SECRET)
YANDEX_DISK_REDIRECT_URI = os.getenv(
    "YANDEX_DISK_REDIRECT_URI",
    "http://127.0.0.1:8000/files/oauth/yandex/callback/",
)

SOCIALACCOUNT_PROVIDERS = {
    "yandex": {
        "APP": {
            "client_id": YANDEX_AUTH_CLIENT_ID,
            "secret": YANDEX_AUTH_CLIENT_SECRET,
        },
        "SCOPE": ["login:email", "login:avatar"],
    }
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "").strip()
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 30)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@classroom.local")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    EMAIL_USE_SSL = False

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Полный путь к soffice / LibreOffice (опционально). Иначе ищется в PATH.
LIBREOFFICE_PATH = os.getenv("LIBREOFFICE_PATH", "").strip()

# ConvertAPI (https://www.convertapi.com/) — облачная конвертация Office→PDF (опционально).
CONVERTAPI_SECRET = os.getenv("CONVERTAPI_SECRET", "").strip()

# ClamAV (clamd): проверка загружаемых файлов. Нужен пакет clamd и работающий демон clamd.
CLAMAV_ENABLED = env_bool("CLAMAV_ENABLED", False)
CLAMAV_FAIL_OPEN = env_bool(
    "CLAMAV_FAIL_OPEN",
    True,
)  # если демон недоступен — всё равно принять файл (с предупреждением)
CLAMAV_SOCKET_PATH = os.getenv("CLAMAV_SOCKET_PATH", "/var/run/clamav/clamd.ctl").strip()
CLAMAV_USE_TCP = env_bool("CLAMAV_USE_TCP", False)
CLAMAV_TCP_HOST = os.getenv("CLAMAV_TCP_HOST", "127.0.0.1").strip()
CLAMAV_TCP_PORT = env_int("CLAMAV_TCP_PORT", 3310)

