# Generated by Django 6.0.1 on 2026-03-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('course', 'Курс'), ('private', 'Личный'), ('group', 'Групповой')], default='private', max_length=20),
        ),
    ]
