from django.urls import path 
from . import views 

app_name ='file_manager'

urlpatterns =[
path('',views.file_list ,name ='file_list'),
path('upload/',views.file_upload ,name ='file_upload'),
path('<int:file_id>/',views.file_detail ,name ='file_detail'),
path('<int:file_id>/download/',views.file_download ,name ='file_download'),
path('<int:file_id>/preview/',views.file_preview ,name ='file_preview'),
path('<int:file_id>/preview/pdf/',views.office_pdf_preview ,name ='office_pdf_preview'),
path('<int:file_id>/versions/<int:version_id>/preview/', views.file_version_preview, name='file_version_preview'),
path('<int:file_id>/versions/<int:version_id>/preview/pdf/', views.file_version_office_pdf_preview, name='file_version_office_pdf_preview'),
path('<int:file_id>/versions/<int:version_id>/inline-viewer/', views.file_version_inline_viewer, name='file_version_inline_viewer'),
path('<int:file_id>/view/',views.file_viewer ,name ='file_viewer'),
path('<int:file_id>/edit/',views.file_edit ,name ='file_edit'),
path('permissions/bulk/', views.files_bulk_permissions, name='files_bulk_permissions'),
path('<int:file_id>/delete/',views.file_delete ,name ='file_delete'),
path('<int:file_id>/version/',views.file_version_create ,name ='file_version_create'),
path('<int:file_id>/versions/compare/', views.file_version_compare, name='file_version_compare'),
path('<int:file_id>/versions/<int:version_id>/restore/', views.file_version_restore, name='file_version_restore'),
path('<int:file_id>/favorite/',views.favorite_toggle ,name ='favorite_toggle'),
path('<int:file_id>/comment/',views.file_comment_create ,name ='file_comment_create'),
path('comment/<int:comment_id>/delete/',views.file_comment_delete ,name ='file_comment_delete'),
path('tags/',views.tag_list ,name ='tag_list'),
path('tags/create/',views.tag_create ,name ='tag_create'),
path('tags/<int:tag_id>/delete/', views.tag_delete, name='tag_delete'),
path('activity/',views.activity_log ,name ='activity_log'),
path('api/storage-quota/',views.get_storage_quota ,name ='storage_quota_api'),
path('oauth/yandex/start/', views.yandex_oauth_start, name='yandex_oauth_start'),
path('oauth/yandex/callback/', views.yandex_oauth_callback, name='yandex_oauth_callback'),
path('oauth/yandex/disconnect/', views.yandex_disconnect, name='yandex_disconnect'),
path('yandex/picker/', views.yandex_file_picker, name='yandex_picker'),
path('<int:file_id>/yandex/export/', views.yandex_export_file, name='yandex_export_file'),
path('download-all/', views.download_all_files_archive, name='download_all_files_archive'),
path('workspaces/', views.workspace_list, name='workspace_list'),
path('workspaces/create/', views.workspace_create, name='workspace_create'),
path('workspaces/users/search/', views.workspace_user_search, name='workspace_user_search'),
path('workspaces/<int:workspace_id>/', views.workspace_detail, name='workspace_detail'),
path(
    'workspaces/<int:workspace_id>/add-participant/',
    views.workspace_add_participant,
    name='workspace_add_participant',
),
path(
    'workspaces/<int:workspace_id>/remove-participant/',
    views.workspace_remove_participant,
    name='workspace_remove_participant',
),
path(
    'workspaces/<int:workspace_id>/remove-file/',
    views.workspace_remove_file,
    name='workspace_remove_file',
),
path('workspaces/<int:workspace_id>/delete/', views.workspace_delete, name='workspace_delete'),
path('<int:file_id>/workspaces/add/', views.workspace_add_file, name='workspace_add_file'),
path('backups/compare/', views.backup_compare, name='backup_compare'),
]